import { Meta, StoryObj } from '@storybook/react-vite';
import { Checkbox } from './Checkbox';
declare const meta: Meta<typeof Checkbox>;
export default meta;
type Story = StoryObj<typeof Checkbox>;
export declare const Default: Story;
export declare const Checked: Story;
export declare const Indeterminate: Story;
export declare const Disabled: Story;
export declare const DisabledChecked: Story;
export declare const WithHelperText: Story;
export declare const SmallSize: Story;
export declare const GroupVertical: Story;
export declare const GroupHorizontal: Story;
