import { Meta, StoryObj } from '@storybook/react-vite';
import { Input } from './Input';
declare const meta: Meta<typeof Input>;
export default meta;
type Story = StoryObj<typeof Input>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const WithHelperText: Story;
export declare const ErrorState: Story;
export declare const Sizes: Story;
export declare const WithLeadingIcon: Story;
export declare const WithBothIcons: Story;
export declare const Disabled: Story;
