import { Meta, StoryObj } from '@storybook/react-vite';
import { Text } from './Text';
declare const meta: Meta<typeof Text>;
export default meta;
type Story = StoryObj<typeof Text>;
export declare const Default: Story;
export declare const HeadingScale: Story;
export declare const BodyScale: Story;
export declare const Colors: Story;
export declare const Weights: Story;
