import { Meta, StoryObj } from '@storybook/react-vite';
import { Radio } from './Radio';
declare const meta: Meta<typeof Radio>;
export default meta;
type Story = StoryObj<typeof Radio>;
export declare const Default: Story;
export declare const Selected: Story;
export declare const Disabled: Story;
export declare const DisabledSelected: Story;
export declare const SmallSize: Story;
export declare const GroupVertical: Story;
export declare const GroupHorizontal: Story;
