import { Meta, StoryObj } from '@storybook/react-vite';
import { ProgressBar } from './ProgressBar';
declare const meta: Meta<typeof ProgressBar>;
export default meta;
type Story = StoryObj<typeof ProgressBar>;
export declare const Default: Story;
export declare const AllVariants: Story;
export declare const Sizes: Story;
export declare const WithLabel: Story;
export declare const Indeterminate: Story;
export declare const Animated: Story;
