import { Meta, StoryObj } from '@storybook/react-vite';
import { Button } from './Button';
declare const meta: Meta<typeof Button>;
export default meta;
type Story = StoryObj<typeof Button>;
export declare const Primary: Story;
export declare const Secondary: Story;
export declare const Ghost: Story;
export declare const Danger: Story;
export declare const Neutral: Story;
export declare const Sizes: Story;
export declare const WithIcons: Story;
export declare const IconOnly: Story;
export declare const Disabled: Story;
export declare const AllVariants: Story;
