import { Meta, StoryObj } from '@storybook/react-vite';
import { Textarea } from './Textarea';
declare const meta: Meta<typeof Textarea>;
export default meta;
type Story = StoryObj<typeof Textarea>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const Error: Story;
export declare const WithCharCount: Story;
export declare const Disabled: Story;
export declare const NoResize: Story;
export declare const AllStates: Story;
