import { Meta, StoryObj } from '@storybook/react-vite';
import { Badge } from './Badge';
declare const meta: Meta<typeof Badge>;
export default meta;
type Story = StoryObj<typeof Badge>;
export declare const Default: Story;
export declare const AllVariants: Story;
export declare const FilledVariants: Story;
export declare const Sizes: Story;
export declare const WithDot: Story;
export declare const WithIcon: Story;
